title: Shivam Gautam
description: Hi! My name is Shivam and I am a graduate student studying Data Science. I have a passion for AI/Machine learning and love working with data since it is the foundation of AI/ML. I aim to display my interest in the field through my projects which implement use of Python, SQL, BI and cloud deployment and hope to apply my skills in a professional environment. 
show_downloads: true
theme: jekyll-theme-minimal
