title: Shivam Gautam
description: Hi! My name is Shivam and I am a graduate student studying Data Science. I have a passion for AI/Machine learning. I also love working with data since it is the foundation of AI/ML. Ever since I discovered the fundementals and possibilities of machine learning, I have had a burning interest in applying what I know about data to the field and learning more about working with data. I aim to display this through some of my projects and apply my skills in a professional environment.
show_downloads: true
theme: jekyll-theme-minimal
